esphome:
  name: firebeetle2-bitcoin75

esp32:
  board: esp32-c6-devkitc-1
  flash_size: 4MB
  variant: esp32c6
  framework:
    type: esp-idf
    version: "5.3.1"
    platform_version: 6.9.0
    sdkconfig_options:
      CONFIG_ESPTOOLPY_FLASHSIZE_4MB: y

mdns:

web_server:
  port: 80

# api:
#   encryption:
#     key: !secret firebeetle2_75in_api_encryption_key

# ota:
#   platform: esphome
#   password: !secret firebeetle2_75in_ota_password

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
#   fast_connect: true

api:
  encryption:
    key: "${FIREBEETLE2_75IN_API_ENCRYPTION_KEY}" # Placeholder for GitHub workflow

ota:
  platform: esphome
  password: "${FIREBEETLE2_75IN_OTA_PASSWORD}" # Placeholder for GitHub workflow

wifi:
  ssid: "${WIFI_SSID}" # Placeholder for GitHub workflow
  password: "${WIFI_PASSWORD}" # Placeholder for GitHub workflow
  fast_connect: true

logger:
  level: INFO # Set logging level (DEBUG for verbose output)
  baud_rate: 115200  # Set the baud rate for logging output

output:
  - platform: gpio
    pin: 15
    id: onboard_led

light:
  - platform: binary
    id: onboard_light
    output: onboard_led

interval:
  - interval: 5s
    then:
      - logger.log:
          level: INFO
          format: "Adam Toggling LED"
      - light.toggle: onboard_light

spi:
  # clk_pin: 23
  # mosi_pin: 22 # DIN
  clk_pin: 4
  mosi_pin: 6 # DIN

font:
  - file: "gfonts://Roboto"
    id: font1
    size: 24

color:
  - id: colour_white
    hex: "000000"

display:
  - platform: waveshare_epaper
    model: 7.50inV2
    # cs_pin: 5
    # dc_pin: 16
    # busy_pin:
    #   number: 18
    #   inverted: true
    # reset_pin: 2
    cs_pin: 7
    dc_pin: 1
    busy_pin:
      number: 3
      # inverted: true
    reset_pin: 2
    reset_duration: 2ms
    rotation: 0
    update_interval: 1min
    id: adam_epaper1
    lambda: |-
      ESP_LOGI("display", ">>> DISPLAY UPDATE <<<");
      it.fill(id(colour_white)); 
      it.print(10, 10, id(font1), "Hello ePaper!");
